### PR TITLE
Do not logout in case of 403 error

### PR DESCRIPTION
**Pull request by mushtaqak**
[ENT-1753](https://openedx.atlassian.net/browse/ENT-1753)

### CODE REVIEW

**Comment by adamstankiewicz** [comment]
Following up here after a Slack discussion with Architecture. The consensus for a path forward is as follows:

* Instead of making the logout logic configurable through the auth config, we should remove the logout redirect logic from this repo. Then, the consuming MFEs of this package could handle 401/403s on using their own business logic, rather than `edx/frontend-auth` forcing the logout.
* This would be done by removing  the `handleUnauthorizedAPIResponse` function and where that function is called in the axios response interceptor.

**Note:** This would be a breaking change and should be a major version bump.

**Comment by mushtaqak** [comment]
@adamstankiewicz @abutterworth Do you guys think, we can proceed this in the meantime https://github.com/edx/frontend-auth/pull/29 is merged ... Just wondering thing to go out ...

**Comment by abutterworth** [comment]
@mushtaqak I'm going to try to merge #29 today. If I can't get there, I'll put a thumb on this to unblock you.

**Comment by adamstankiewicz** [comment]
Looks like #29 was merged today; thanks @abutterworth! 😄

@mushtaqak We should be able to close this PR, and then update https://github.com/edx/edx-portal/pull/205 to use the new callback configuration added in #29.

**Pull request closed without merging**
